import { NextRequest, NextResponse } from "next/server";
import { db, DbSearch } from "@/lib/db";

function buildMarkdown(s: DbSearch): string {
  const lines: string[] = [];
  lines.push(`# OSINT Intelligence Report`);
  lines.push(`**Target:** ${s.entityName}  `);
  lines.push(`**Type:** ${s.entityType}  `);
  lines.push(`**Generated:** ${new Date().toLocaleString()}  `);
  lines.push(`**Report ID:** \`${s.id}\``);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Executive Summary");
  lines.push("");
  lines.push(s.summary ?? "No summary available.");
  lines.push("");
  lines.push("## Risk Assessment");
  lines.push("");
  lines.push(`| Category | Score |`);
  lines.push(`|---|---|`);
  lines.push(`| Overall | ${s.riskOverall}/100 |`);
  lines.push(`| Social | ${s.riskSocial}/100 |`);
  lines.push(`| Technical | ${s.riskTech}/100 |`);
  lines.push(`| Regulatory | ${s.riskReg}/100 |`);
  lines.push("");
  lines.push("## Findings");
  lines.push("");
  for (const f of (s.findings ?? [])) {
    lines.push(`### ${f.title}`);
    lines.push(`*${f.sourceName} · ${f.category} · Risk: ${f.riskLevel} · Status: ${f.status}*`);
    lines.push("");
    lines.push(f.value);
    if (f.sourceUrl) lines.push(`\nSource: ${f.sourceUrl}`);
    lines.push("");
  }
  lines.push("---");
  lines.push("*Generated by OSINT Intelligence Platform*");
  return lines.join("\n");
}

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const result = await db.getSearch(id);
    if (!result) return NextResponse.json({ success: false, error: "Not found" }, { status: 404 });

    const format = new URL(req.url).searchParams.get("format") ?? "json";
    if (format === "markdown") {
      const md = buildMarkdown(result);
      return new NextResponse(md, {
        headers: {
          "Content-Type": "text/markdown",
          "Content-Disposition": `attachment; filename="osint-${result.entityName.replace(/\s+/g,"-")}.md"`,
        },
      });
    }
    return NextResponse.json({ success: true, data: { result } });
  } catch {
    return NextResponse.json({ success: false, error: "Report generation failed" }, { status: 500 });
  }
}
