/**
 * Report Generator
 * Produces Markdown reports from SearchResult objects.
 * PDF generation happens client-side via jsPDF.
 */

import { SearchResult, AdapterResult, DataPoint, RiskLevel } from "@/types";

const RISK_EMOJI: Record<RiskLevel, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🟢",
  unknown: "⚪",
};

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleString("en-US", {
      year: "numeric", month: "short", day: "numeric",
      hour: "2-digit", minute: "2-digit",
    });
  } catch {
    return iso;
  }
}

function riskBar(score: number): string {
  const filled = Math.round(score / 10);
  return "█".repeat(filled) + "░".repeat(10 - filled) + ` ${score}/100`;
}

export function generateMarkdownReport(result: SearchResult): string {
  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push(`# OSINT Intelligence Report`);
  lines.push(`**Target:** ${result.entity.name}  `);
  lines.push(`**Type:** ${result.entity.type === "company" ? "Company / Organization" : "Individual"}  `);
  lines.push(`**Generated:** ${formatDate(result.completedAt ?? result.createdAt)}  `);
  lines.push(`**Report ID:** \`${result.id}\``);
  lines.push("");
  lines.push("---");
  lines.push("");

  // ── Executive Summary ───────────────────────────────────────────────────────
  lines.push("## Executive Summary");
  lines.push("");
  lines.push(result.summary);
  lines.push("");

  // ── Risk Score ──────────────────────────────────────────────────────────────
  lines.push("## Risk Assessment");
  lines.push("");
  lines.push(`| Category | Score | Bar |`);
  lines.push(`|---|---|---|`);
  lines.push(`| **Overall** | **${result.riskScore.overall}/100** | \`${riskBar(result.riskScore.overall)}\` |`);
  lines.push(`| Social & Public Footprint | ${result.riskScore.breakdown.social}/100 | \`${riskBar(result.riskScore.breakdown.social)}\` |`);
  lines.push(`| Technical Infrastructure | ${result.riskScore.breakdown.technical}/100 | \`${riskBar(result.riskScore.breakdown.technical)}\` |`);
  lines.push(`| Regulatory & Contextual | ${result.riskScore.breakdown.regulatory}/100 | \`${riskBar(result.riskScore.breakdown.regulatory)}\` |`);
  lines.push("");

  if (result.riskScore.criticalRiskCount > 0) {
    lines.push(`> ⚠️ **${result.riskScore.criticalRiskCount} CRITICAL finding(s)** require immediate attention.`);
    lines.push("");
  }

  // ── Findings by Category ────────────────────────────────────────────────────
  const categories: { id: string; label: string }[] = [
    { id: "social", label: "Social & Public Footprint" },
    { id: "technical", label: "Technical Infrastructure" },
    { id: "regulatory", label: "Regulatory & Contextual" },
  ];

  for (const cat of categories) {
    const catResults = result.results.filter((r) => r.category === cat.id);
    if (catResults.length === 0) continue;

    lines.push(`## ${cat.label}`);
    lines.push("");

    for (const adapter of catResults) {
      lines.push(`### ${adapter.adapterName}`);
      lines.push(`*Status: ${adapter.status} | Fetched: ${formatDate(adapter.fetchedAt)}*`);
      lines.push("");

      if (adapter.status === "error") {
        lines.push(`> ❌ Error: ${adapter.error}`);
        lines.push("");
        continue;
      }

      if (adapter.data.length === 0) {
        lines.push("> No data points collected.");
        lines.push("");
        continue;
      }

      lines.push("| Risk | Finding | Details | Source | Confidence |");
      lines.push("|---|---|---|---|---|");

      for (const dp of adapter.data) {
        const source = dp.sourceUrl ? `[Link](${dp.sourceUrl})` : "—";
        const safeValue = dp.value.replace(/\|/g, "\\|").replace(/\n/g, " ");
        lines.push(
          `| ${RISK_EMOJI[dp.riskLevel]} ${dp.riskLevel.toUpperCase()} | **${dp.title}** | ${safeValue} | ${source} | ${dp.confidence} |`
        );
      }
      lines.push("");
    }
  }

  // ── Methodology ─────────────────────────────────────────────────────────────
  lines.push("## Methodology");
  lines.push("");
  lines.push(
    "This report was generated using automated OSINT (Open-Source Intelligence) techniques. " +
    "All data was collected from publicly accessible sources. " +
    "Risk scores are computed algorithmically based on the nature and severity of findings."
  );
  lines.push("");
  lines.push("**Data Sources Used:**");
  for (const r of result.results) {
    lines.push(`- **${r.adapterName}** (${r.category}): ${r.data.length} data point(s) — status: ${r.status}`);
  }
  lines.push("");
  lines.push("---");
  lines.push("*Generated by OSINT Intelligence Platform*");

  return lines.join("\n");
}
